export const en = {
  // General
  'app.name': 'TaniTrack',
  'app.tagline': 'Agricultural Supply Chain Management',
  'action.search': 'Search',
  'action.filter': 'Filter',
  'action.view': 'View',
  'action.edit': 'Edit',
  'action.delete': 'Delete',
  'action.save': 'Save',
  'action.cancel': 'Cancel',
  'action.close': 'Close',
  'action.add': 'Add',
  'action.back': 'Back',
  'action.next': 'Next',
  'action.submit': 'Submit',
  'action.download': 'Download',
  'action.upload': 'Upload',
  'action.clear': 'Clear',
  'action.confirm': 'Confirm',
  'action.deny': 'Deny',
  'action.refresh': 'Refresh',
  'action.details': 'Details',
  'action.showAll': 'Show All',
  'action.showMore': 'Show More',
  'action.saving': 'Saving...',

  // Navigation
  'nav.dashboard': 'Dashboard',
  'nav.commodities': 'Commodities',
  'nav.balance': 'Balance',
  'nav.transactions': 'Transactions',
  'nav.orderbook': 'Order Book',
  'nav.prices': 'Prices',
  'nav.shipping': 'Shipping',
  'nav.profile': 'Profile',
  'nav.logout': 'Logout',
  'nav.settings': 'Settings',
  'nav.notifications': 'Notifications',
  'nav.home': 'Home',
  'nav.orderBook': 'Order Book',
  'nav.price': 'Commodity Prices',
  'nav.market': 'Market',
  'nav.farmer': 'Farmer',
  'nav.buyer': 'Buyer',

  // Login
  'login.description': "Agricultural Management App for Farmers' Prosperity",
  'login.qrscan.command': 'Aim the camera at the QR code on your Tani Card.',
  'login.qrscan.result': 'QR code will fill in TaniId and Email automatically.',
  'login.title': 'Login to TaniTrack',
  'login.otpPrompt': 'Enter the OTP code sent to your email',
  'login.emailPrompt': 'Enter your email to get started',
  'login.taniIdPrompt': 'Enter your TaniId to login',
  'login.qrscan.title': 'Scan QR Code Tani Card',
  'login.noAccount': "Don't have an account? ",
  'login.registerNow': 'Register now',
  'login.howTo': 'How to Login',
  'login.step1.email': 'Enter your registered Email in TaniTrack',
  'login.step1.taniId': 'Enter your registered TaniId in TaniTrack',
  'login.step1.qr': 'Scan your registered Tani Card in TaniTrack',
  'login.step2': 'Enter the OTP code sent to your email',
  'login.otpSentTitle': 'OTP code has been sent!',
  'login.otpSentDesc': 'Please enter the OTP code sent to your email',
  'login.emailFailed': 'Failed to login with email',
  'login.emailFailedDesc': 'An error occurred while logging in with email',
  'login.profileNotRegistered': 'Profile not registered',
  'login.completeProfileFirst': 'Please complete your profile first',
  'login.success': 'Login successful!',
  'login.welcome': 'Welcome back to TaniTrack',
  'login.invalidOtp': 'Invalid OTP code',
  'login.failed': 'Login failed',
  'login.otpResentTitle': 'OTP has been resent',
  'login.otpResentDesc': 'Please check your email',
  'login.otpResendFailed': 'Failed to resend OTP',
  'login.otpResendFailedDesc': 'An error occurred while resending OTP',
  'login.taniIdRequired': 'TaniId is required',
  'login.taniIdFailed': 'Failed to login with TaniId',
  'login.taniIdFailedDesc':
    'An error occurred while logging in with TaniId, please check your TaniId or use email login',

  //   Registration
  'register.title': 'Registration',
  'register.as': 'Register as',
  'register.farmer': 'Farmer',
  'register.farmerDesc': 'Register as a farmer to sell agricultural products',
  'register.buyer': 'Buyer',
  'register.buyerDesc': 'Register as a buyer to purchase agricultural products',
  'register.backToRole': 'Back to role selection',
  'register.success': 'Registration Successful!',
  'register.profileSaved': 'Your profile has been successfully saved',
  'register.redirecting': 'Redirecting to dashboard...',
  'register.completeProfile': 'Complete Profile',
  'register.completeProfileDesc': 'Complete your profile information',
  'register.withEmail': 'Registration with email',
  'register.chooseRole': 'Choose your role on the platform',
  'benefits.title': 'Benefits of using TaniTrack:',
  'benefits.directTrade': 'Sell ​​and Buy agricultural products directly',
  'benefits.traceable': 'Traceable product origins',
  'benefits.sustainable': 'Support agriculture until it is sustainable',
  'profile.nationalId': 'ID Card Number',
  'profile.nationalIdPlaceholder': 'Enter ID card number',
  'profile.fullName': 'Full Name',
  'profile.fullNamePlaceholder': 'Enter full name',
  'profile.phone': 'Phone/Whatsapp Number',
  'profile.phonePlaceholder': 'Enter phone number',
  'profile.address': 'Main Address',
  'profile.addressPlaceholder': 'Enter address',
  'profile.processing': 'Processing...',
  'profile.save': 'Save Profile',

  // Commodities
  'commodities.title': 'Commodities',
  'commodities.subtitle': 'Manage your agricultural commodities',
  'commodities.add': 'Add Commodity',
  'commodities.name': 'Name',
  'commodities.type': 'Type',
  'commodities.quantity': 'Quantity',
  'commodities.location': 'Location',
  'commodities.grade': 'Grade',
  'commodities.action': 'Action',
  'commodities.search': 'Search commodities...',
  'commodities.detail': 'Commodity Details',
  'commodities.qrcode': 'QR Code',
  'commodities.unit': 'Unit',
  'commodities.created': 'Created Date',
  'commodities.harvestDate': 'Harvest Date',
  'commodities.upload.image': 'Upload commodity image',
  'commodities.upload.grade': 'Upload grading file',
  'commodities.list': 'Commodity List',
  'commodities.notfound': 'No commodities found',
  'commodities.history': 'Transaction History',
  'commodities.export': 'Export Data',
  'commodities.import': 'Import Data',
  'commodities.filter': 'Filter Commodities',
  'commodities.sort': 'Sort By',
  'commodities.harvest': 'Harvest Date',
  'commodities.origin': 'Origin',
  'commodities.category': 'Category',
  'commodities.imageUrl': 'Image URL',
  'commodities.stock': 'Total Stock',
  'commodities.pricePerUnit': 'Price per Unit',
  'commodities.price': 'Price',
  'commodities.certifications': 'Certifications',
  'commodities.description': 'Description',
  'commodities.qrcodeDesc': 'Use this QR Code to track your commodity.',
  'commodities.addDesc': 'Fill out the form below to add a new commodity to your list.',
  'commodities.namePlaceholder': 'Enter commodity name',
  'commodities.unitPlaceholder': 'Select unit',
  'commodities.categoryPlaceholder': 'Select category',
  'commodities.imageUrlPlaceholder': 'Commodity image URL',
  'commodities.gradePlaceholder': 'Grade level e.g. A, B, C',
  'commodities.harvestDatePlaceholder': 'Pick a date',
  'commodities.descriptionPlaceholder': 'Commodity description',
  'commodities.basePrice': 'Base Price',
  'commodities.stockPlaceholder': 'Enter stock',
  'commodities.setBulkPrice': 'Set Bulk Price',
  'commodities.bulkPrice': 'Bulk Price',
  'commodities.addBulkPrice': 'Add Bulk Price',
  'commodities.bulkPriceList': 'Bulk Price List',
  'commodities.noBulkPrice': 'No bulk price yet',
  'commodities.addBulkPriceHint': 'Add bulk prices to attract large buyers',
  'commodities.basePriceInfo': 'This price applies for standard purchases.',
  'commodities.minQuantity': 'Minimum Quantity',
  'commodities.minQuantityPlaceholder': '100',
  'commodities.bulkPricePerUnit': 'Price per {{unit}}',
  'commodities.bulkPriceAuto': 'Price will be automatically applied based on purchase quantity.',
  'commodities.saveBulkPrice': 'Save Bulk Price',
  'commodities.error': 'Error',
  'commodities.nameRequired': 'Commodity name is required',
  'commodities.addSuccessTitle': 'Commodity added successfully',
  'commodities.addSuccessDesc': '{{name}} has been added to your commodity list',
  'commodities.addFailed': 'Failed to add commodity',
  'commodities.attention': 'Attention',
  'commodities.fillBasePriceAndUnit': 'Please fill in the base price and unit first',

  // Market
  'market.title': 'Commodity Market',
  'market.subtitle': 'Explore and purchase quality agricultural commodities directly from farmers.',
  'market.seeCurrentPrices': 'See Current Prices',
  'market.searchPlaceholder': 'Search commodities...',
  'market.filter': 'Filter',
  'market.noImage': 'No Image',
  'market.farmer': 'Farmer:',
  'market.location': 'Location:',
  'market.stock': 'Stock:',
  'market.details': 'Details',
  'market.loadMore': 'Load More',
  'market.loading': 'Loading commodities...',
  'market.noCommodities': 'No commodities found',
  'market.search': 'Search commodities...',
  'market.sort': 'Sort',
  'market.currentPrices': 'See Current Prices',
  'market.price': 'Price',
  'market.buy': 'Buy',
  'market.noResults': 'No commodities found',
  'market.minOrder': 'Minimum order',
  'market.certifications': 'Certifications',
  'market.harvestDate': 'Harvest Date',
  'market.variety': 'Variety',
  'market.grade': 'Grade',
  'market.description': 'Description',
  'market.nutrition': 'Nutrition',
  'market.storage': 'Storage',
  'market.buyNow': 'Buy Now',
  'market.contactFarmer': 'Contact Farmer',
  'market.viewAllProducts': 'View All Products',
  'market.farmerInfo': 'Farmer Information',
  'market.memberSince': 'Member since',
  'market.transactions': 'transactions',
  'market.reviews': 'Customer Reviews',
  'market.noReviews': 'No reviews yet',
  'market.backToMarket': 'Back to Market',
  'market.notFound': 'Commodity not found',
  'marketDetail.loading': 'Loading commodity details...',
  'marketDetail.notFound': 'Commodity not found',
  'marketDetail.backToMarket': 'Back to Market',
  'marketDetail.noImage': 'No Image',
  'marketDetail.farmer': 'Farmer',
  'marketDetail.location': 'Location',
  'marketDetail.stock': 'Stock',
  'marketDetail.harvestDate': 'Harvest Date',
  'marketDetail.loadingPrice': 'Loading price...',
  'marketDetail.price': 'Price',
  'marketDetail.totalPrice': 'Total Price',
  'marketDetail.processing': 'Processing...',
  'marketDetail.placeOrder': 'Place Order & Pay',
  'marketDetail.description': 'Description',
  'marketDetail.noDescription': 'No description available.',
  'marketDetail.farmerInfo': 'Farmer Information',
  'marketDetail.memberSince': 'Member since',
  'marketDetail.transactions': 'transactions',
  'marketDetail.contactFarmer': 'Contact Farmer',
  'marketDetail.viewAllProducts': 'View All Products',
  'marketDetail.error': 'Error',
  'marketDetail.notLoggedIn': 'User not logged in or profile incomplete.',
  'marketDetail.noCommodityOrQuantity': 'Commodity data not loaded or quantity not selected.',
  'marketDetail.processingOrder': 'Processing Order...',
  'marketDetail.pleaseWait': 'Please wait.',
  'marketDetail.failedPrepareOrder': 'Failed to prepare order on server.',
  'marketDetail.awaitingPayment': 'Awaiting Payment...',
  'marketDetail.confirmInWallet': 'Please confirm the transaction in your wallet.',
  'marketDetail.paymentSecured': 'Payment Secured!',
  'marketDetail.escrowInitialized': 'Escrow initialized. Tx: {{tx}}...',
  'marketDetail.missingPda': 'Missing PDA address after transaction.',
  'marketDetail.orderUpdated': 'Order Updated',
  'marketDetail.convexUpdated': 'Convex records updated.',
  'marketDetail.failedUpdateConvex': 'Failed to update order status in Convex.',
  'marketDetail.paymentFailed': 'Payment Failed',
  'marketDetail.couldNotInitEscrow': 'Could not initialize escrow.',
  'marketDetail.txSubmitted': 'Transaction Submitted',
  'marketDetail.txAwaiting': 'Tx: {{tx}}... Awaiting confirmation.',
  'marketDetail.orderFailed': 'Order Failed',
  'marketDetail.couldNotPlaceOrder': 'Could not place order.',

  // Transactions
  'transactions.title': 'Transactions',
  'transactions.subtitle': 'Manage your commodity transactions',
  'transactions.id': 'Transaction ID',
  'transactions.type': 'Type',
  'transactions.commodity': 'Commodity',
  'transactions.quantity': 'Quantity',
  'transactions.price': 'Price',
  'transactions.status': 'Status',
  'transactions.buyer': 'Buyer',
  'transactions.seller': 'Seller',
  'transactions.date': 'Date',
  'transactions.action': 'Action',
  'transactions.search': 'Search transactions...',
  'transactions.detail': 'Transaction Details',
  'transactions.all': 'All',
  'transactions.pending': 'Pending',
  'transactions.processed': 'Processed',
  'transactions.completed': 'Completed',
  'transactions.canceled': 'Canceled',
  'transactions.total': 'Total Price',
  'transactions.terms': 'Terms & Conditions',
  'transactions.notfound': 'No transactions found',
  'transactions.filters': 'Transaction Filters',
  'transactions.payment': 'Payment Method',
  'transactions.timeline': 'Transaction Timeline',
  'transactions.documents': 'Documents',
  'transactions.notes': 'Notes',
  'transactions.invoice': 'Invoice',
  'transactions.empty': 'No transactions found',
  'transactions.new': 'New Transaction',
  'transactions.regular': 'Regular',
  'transactions.list': 'Transaction List',
  'transactions.print': 'Print Transaction',

  // Order Book
  'orderbook.title': 'Order Book',
  'orderbook.subtitle': 'View and accept commodity requests from buyers',
  'orderbook.id': 'Order ID',
  'orderbook.counterparty': 'Counterparty',
  'orderbook.seller': 'Seller',
  'orderbook.amount': 'Total Amount',
  'orderbook.buyer': 'Buyer',
  'orderbook.commodity': 'Commodity',
  'orderbook.quantity': 'Quantity',
  'orderbook.grade': 'Required Grade',
  'orderbook.delivery': 'Delivery Date',
  'orderbook.expiry': 'Expiry Date',
  'orderbook.status': 'Status',
  'orderbook.action': 'Action',
  'orderbook.search': 'Search order book...',
  'orderbook.detail': 'Order Book Details',
  'orderbook.list': 'Order Book List',
  'orderbook.all': 'All',
  'orderbook.open': 'Open',
  'orderbook.accepted': 'Accepted',
  'orderbook.completed': 'Completed',
  'orderbook.expired': 'Expired',
  'orderbook.terms': 'Terms & Conditions',
  'orderbook.notfound': 'No order book entries found',
  'orderbook.filter': 'Filter Orders',
  'orderbook.sort': 'Sort By',
  'orderbook.create': 'Create Order',
  'orderbook.price': 'Asking Price',
  'orderbook.total': 'Total Value',
  'orderbook.offers': 'Offers',
  'orderbook.respond': 'Respond to Order',

  // Shipping
  'shipping.title': 'Shipping',
  'shipping.subtitle': 'Track and manage your shipments',
  'shipping.id': 'Shipment ID',
  'shipping.origin': 'Origin',
  'shipping.destination': 'Destination',
  'shipping.status': 'Status',
  'shipping.carrier': 'Carrier',
  'shipping.tracking': 'Tracking Number',
  'shipping.departureDate': 'Departure Date',
  'shipping.arrivalDate': 'Estimated Arrival',
  'shipping.commodity': 'Commodity',
  'shipping.weight': 'Weight',
  'shipping.cost': 'Shipping Cost',
  'shipping.documents': 'Documents',
  'shipping.notfound': 'No shipments found',
  'shipping.create': 'Create Shipment',
  'shipping.detail': 'Shipment Details',
  'shipping.updateStatus': 'Update Status',
  'shipping.trackShipment': 'Track Shipment',
  'shipping.vehicle': 'Vehicle Type',
  'shipping.driverInfo': 'Driver Information',
  'shipping.contact': 'Contact',
  'shipping.instructions': 'Special Instructions',
  'shipping.route': 'Route Information',
  'shipping.stops': 'Stops',
  'shipping.history': 'Status History',

  // Prices
  'prices.title': 'Market Prices',
  'prices.subtitle': 'View current commodity prices',
  'prices.commodity': 'Commodity',
  'prices.category': 'Category',
  'prices.currentPrice': 'Current Price',
  'prices.change': '24h Change',
  'prices.volume': '24h Volume',
  'prices.high': '24h High',
  'prices.low': '24h Low',
  'prices.chart': 'Price Chart',
  'prices.history': 'Price History',
  'prices.forecast': 'Price Forecast',
  'prices.market': 'Market',
  'prices.date': 'Last Updated',
  'prices.source': 'Data Source',
  'prices.filter': 'Filter Prices',
  'prices.compare': 'Compare',
  'prices.watchlist': 'Add to Watchlist',
  'prices.trends': 'Market Trends',
  'prices.notifications': 'Price Alerts',
  'prices.name': 'Name',
  'prices.price': 'Price',
  'prices.unit': 'Unit',
  'prices.grade': 'Grade',
  'prices.action': 'Action',
  'prices.notfound': 'No commodities found',
  'prices.searchPlaceholder': 'Search commodity or region...',
  'prices.viewDetail': 'View price details',

  // Status labels
  'status.open': 'Open',
  'status.accepted': 'Accepted',
  'status.completed': 'Completed',
  'status.expired': 'Expired',
  'status.canceled': 'Canceled',
  'status.pending': 'Pending',
  'status.confirmed': 'Confirmed',
  'status.paid': 'Paid',
  'status.shipped': 'Shipped',
  'status.received': 'Received',
  'status.processing': 'Processing',
  'status.notshipped': 'Not Shipped',
  'status.shipping': 'Shipping',
  'status.delivered': 'Delivered',
  'status.inTransit': 'In Transit',
  'status.outForDelivery': 'Out for Delivery',
  'status.failed': 'Failed',
  'status.delayed': 'Delayed',
  'status.returned': 'Returned',
  'status.approved': 'Approved',
  'status.rejected': 'Rejected',
  'status.draft': 'Draft',
  'status.onHold': 'On Hold',
  'status.negotiating': 'Negotiating',

  // Dashboard
  'dashboard.title': 'Dashboard',
  'dashboard.welcome': 'Welcome back,',
  'dashboard.summary': 'Summary Income',
  'dashboard.recentTransactions': 'Recent Transactions',
  'dashboard.pendingOrders': 'Pending Orders',
  'dashboard.upcomingShipments': 'Upcoming Shipments',
  'dashboard.marketInsights': 'Market Insights',
  'dashboard.commodityStatus': 'Commodity Status',
  'dashboard.analytics': 'Analytics',
  'dashboard.quickActions': 'Quick Actions',
  'dashboard.alerts': 'Alerts',
  'dashboard.recommendations': 'Recommendations',
  'dashboard.expenseSummary': 'Expense Summary',
  'transactions.inDelivery': 'In Delivery',
  'transactions.status.selesai': 'Completed',
  'transactions.status.dibatalkan': 'Cancelled',
  'transactions.status.negosiasi': 'Negotiation',
  'transactions.status.menunggu_konfirmasi': 'Awaiting Confirmation',
  'transactions.status.dikonfirmasi': 'Confirmed',
  'transactions.status.dibayar': 'Paid',
  'transactions.status.persiapan_pengiriman': 'Preparing Shipment',
  'transactions.status.sedang_dikirim': 'Shipping',
  'transactions.status.sudah_dikirim': 'Shipped',
  'transactions.status.diterima': 'Received',

  // Profile/Account
  'profile.title': 'Profile',
  'profile.personalInfo': 'Personal Information',
  'profile.company': 'Company Information',
  'profile.security': 'Security',
  'profile.preferences': 'Preferences',
  'profile.notifications': 'Notifications',
  'profile.paymentMethods': 'Payment Methods',
  'profile.accountHistory': 'Account History',
  'profile.documents': 'Documents',
  'profile.settings': 'Account Settings',
  'profile.help': 'Help & Support',
  'profile.logout': 'Logout',
  'profile.editProfile': 'Edit Profile',
  'profile.changePassword': 'Change Password',
  'profile.language': 'Language',
  'profile.theme': 'Theme',
  'profile.verifications': 'Verifications',

  // Balance/Finance
  'balance.title': 'Balance',
  'balance.available': 'Available Balance',
  'balance.pending': 'Pending',
  'balance.totalValue': 'Total Value',
  'balance.transactions': 'Transaction History',
  'balance.withdraw': 'Withdraw',
  'balance.deposit': 'Deposit',
  'balance.transfer': 'Transfer',
  'balance.statement': 'Statement',
  'balance.paymentMethods': 'Payment Methods',
  'balance.settings': 'Payment Settings',
  'balance.currency': 'Currency',
  'balance.exchange': 'Exchange Rate',

  // Time and dates
  'time.today': 'Today',
  'time.yesterday': 'Yesterday',
  'time.tomorrow': 'Tomorrow',
  'time.thisWeek': 'This Week',
  'time.lastWeek': 'Last Week',
  'time.thisMonth': 'This Month',
  'time.lastMonth': 'Last Month',
  'time.thisYear': 'This Year',
  'time.lastYear': 'Last Year',
  'time.custom': 'Custom Range',

  // Charts and Analytics
  'charts.dailyPrices': 'Daily Prices',
  'charts.monthlyVolume': 'Monthly Volume',
  'charts.commodityDistribution': 'Commodity Distribution',
  'charts.transactionTrends': 'Transaction Trends',
  'charts.marketComparison': 'Market Comparison',
  'charts.supplyDemand': 'Supply & Demand',
  'charts.seasonalTrends': 'Seasonal Trends',
  'charts.priceForecasts': 'Price Forecasts',
  'charts.exportImport': 'Export/Import Ratio',
  'charts.incomeExpenses': 'Income & Expenses',

  // Errors and notifications
  'error.generic': 'An error occurred',
  'error.notFound': 'Not found',
  'error.unauthorized': 'Unauthorized access',
  'error.forbidden': 'Access forbidden',
  'error.validation': 'Validation error',
  'error.network': 'Network error',
  'error.serverError': 'Server error',
  'error.timeout': 'Request timeout',
  'error.unavailable': 'Service unavailable',
  'success.saved': 'Successfully saved',
  'success.created': 'Successfully created',
  'success.updated': 'Successfully updated',
  'success.deleted': 'Successfully deleted',
  'info.processing': 'Processing your request',
  'info.noData': 'No data available',
  'warning.unsaved': 'You have unsaved changes',

  // Transaction Flow Explainer
  'flow.title': 'Transaction Process',
  'flow.subtitle': "Here's how the transaction process works from start to finish:",
  'flow.current': 'Current Step',
  'flow.helpTitle': 'Need help?',
  'flow.helpText':
    'If you need assistance with any step of the process, please contact our support team through the help center or WhatsApp.',

  'flow.pending.title': '1. Order Received',
  'flow.pending.description':
    'A buyer has placed an order for your commodity. Review the order details and decide to accept or reject it.',

  'flow.confirmed.title': '2. Order Confirmed',
  'flow.confirmed.description':
    "You've confirmed the order. The buyer has been notified and awaits further information.",

  'flow.negotiating.title': '3. Price Negotiation',
  'flow.negotiating.description':
    'Discuss and negotiate price terms with the buyer until both parties are satisfied.',

  'flow.paid.title': '4. Payment Received',
  'flow.paid.description':
    'The buyer has made the payment for the order. You can now proceed with preparing the shipment.',

  'flow.processing.title': '5. Preparing Shipment',
  'flow.processing.description':
    'Prepare the ordered commodities for shipping. Ensure proper packaging and documentation.',

  'flow.shipping.title': '6. Shipment in Transit',
  'flow.shipping.description':
    'The commodities are on their way to the buyer. Tracking information has been provided to the buyer.',

  'flow.shipped.title': '7. Shipment Delivered',
  'flow.shipped.description': "The shipment has been delivered to the buyer's specified address.",

  'flow.received.title': '8. Order Received',
  'flow.received.description':
    'The buyer has confirmed receipt of the commodities and is reviewing them.',

  'flow.completed.title': '9. Transaction Completed',
  'flow.completed.description':
    'The transaction has been successfully completed. The funds have been released to your account.',
  'transactions.updatedAt': 'Updated Date',
  'transactions.summary': 'Transaction Summary',
};
