export const id = {
  // General
  'app.name': 'TaniTrack',
  'app.tagline': 'Manajemen Rantai Pasok Pertanian',
  'action.search': 'Cari',
  'action.filter': 'Filter',
  'action.view': 'Lihat',
  'action.edit': 'Edit',
  'action.delete': 'Hapus',
  'action.save': 'Simpan',
  'action.cancel': 'Batal',
  'action.close': 'Tutup',
  'action.add': 'Tambah',
  'action.back': 'Kembali',
  'action.next': 'Selanjutnya',
  'action.submit': 'Kirim',
  'action.download': 'Unduh',
  'action.upload': 'Unggah',
  'action.clear': 'Bersihkan',
  'action.confirm': 'Konfirmasi',
  'action.deny': 'Tolak',
  'action.refresh': 'Segarkan',
  'action.details': 'Detail',
  'action.showAll': 'Tampilkan Semua',
  'action.showMore': 'Tampilkan Lebih',
  'action.print': 'Cetak',
  'action.saving': 'Menyimpan...',
  'action.remove': 'Hapus',

  // Navigation
  'nav.dashboard': 'Dasbor',
  'nav.commodities': 'Komoditas',
  'nav.balance': 'Saldo',
  'nav.transactions': 'Transaksi',
  'nav.orderbook': 'Order Book',
  'nav.prices': 'Harga',
  'nav.shipping': 'Pengiriman',
  'nav.profile': 'Profil',
  'nav.logout': 'Keluar',
  'nav.settings': 'Pengaturan',
  'nav.notifications': 'Notifikasi',
  'nav.home': 'Beranda',
  'nav.orderBook': 'Order Book',
  'nav.price': 'Harga Komoditas',
  'nav.market': 'Pasar',
  'nav.farmer': 'Petani',
  'nav.buyer': 'Pembeli',

  // Login
  'login.description': 'Aplikasi Pengelolaan Pertanian untuk Kemakmuran Petani',
  'login.qrscan.command': 'Arahkan kamera ke kode QR di Kartu Tani Anda.',
  'login.qrscan.result': 'QR code akan mengisi TaniId dan Email secara otomatis.',
  'login.title': 'Masuk ke TaniTrack',
  'login.otpPrompt': 'Masukkan kode OTP yang dikirimkan ke email Anda',
  'login.emailPrompt': 'Masukkan email Anda untuk memulai',
  'login.taniIdPrompt': 'Masukkan TaniId Anda untuk login',
  'login.qrscan.title': 'Pindai Kode QR Kartu Tani',
  'login.noAccount': 'Belum punya akun?',
  'login.registerNow': 'Daftar sekarang',
  'login.howTo': 'Cara Masuk',
  'login.step1.email': 'Masukkan Email terdaftar Anda di TaniTrack',
  'login.step1.taniId': 'Masukkan TaniId terdaftar Anda di TaniTrack',
  'login.step1.qr': 'Pindai Kartu Tani Anda yang terdaftar di TaniTrack',
  'login.step2': 'Masukkan kode OTP yang dikirimkan ke email Anda',
  'login.otpSentTitle': 'Kode OTP telah dikirimkan!',
  'login.otpSentDesc': 'Silakan masukkan kode OTP yang dikirimkan ke email Anda',
  'login.emailFailed': 'Gagal masuk dengan email',
  'login.emailFailedDesc': 'Terjadi kesalahan saat masuk dengan email',
  'login.profileNotRegistered': 'Profil tidak terdaftar',
  'login.completeProfileFirst': 'Silakan lengkapi profil Anda terlebih dahulu',
  'login.success': 'Login berhasil!',
  'login.welcome': 'Selamat datang kembali di TaniTrack',
  'login.invalidOtp': 'Kode OTP tidak valid',
  'login.failed': 'Gagal masuk',
  'login.otpResentTitle': 'OTP telah dikirim ulang',
  'login.otpResentDesc': 'Silakan periksa email Anda',
  'login.otpResendFailed': 'Gagal mengirim ulang OTP',
  'login.otpResendFailedDesc': 'Terjadi kesalahan saat mengirim ulang OTP',
  'login.taniIdRequired': 'TaniId diperlukan',
  'login.taniIdFailed': 'Gagal masuk dengan TaniId',
  'login.taniIdFailedDesc':
    'Terjadi kesalahan saat login dengan TaniId, harap periksa TaniId Anda atau gunakan login email',

  //   Registration
  'register.title': 'Pendaftaran',
  'register.as': 'Daftar Sebagai',
  'register.farmer': 'Petani',
  'register.farmerDesc': 'Daftar sebagai petani untuk menjual produk pertanian',
  'register.buyer': 'Konsumen',
  'register.buyerDesc': 'Daftar sebagai konsumen untuk membeli produk pertanian',
  'register.backToRole': 'Kembali ke pilihan peran',
  'register.success': 'Registrasi Berhasil!',
  'register.profileSaved': 'Profil Anda telah berhasil disimpan',
  'register.redirecting': 'Mengalihkan ke dashboard...',
  'register.completeProfile': 'Lengkapi Profil',
  'register.completeProfileDesc': 'Lengkapi informasi profil Anda',
  'register.withEmail': 'Pendaftaran dengan email',
  'register.chooseRole': 'Pilih peran Anda dalam platform',
  'benefits.title': 'Manfaat menggunakan TaniTrack:',
  'benefits.directTrade': 'Jual dan Beli produk pertanian secara langsung',
  'benefits.traceable': 'Asal-usul produk yang terlacak',
  'benefits.sustainable': 'Dukung agrikultural hingga berkelanjutan',
  'profile.nationalId': 'No. KTP',
  'profile.nationalIdPlaceholder': 'Masukkan nomor KTP',
  'profile.fullName': 'Nama Lengkap',
  'profile.fullNamePlaceholder': 'Masukkan nama lengkap',
  'profile.phone': 'No. HP/Whatsapp',
  'profile.phonePlaceholder': 'Masukkan nomor HP',
  'profile.address': 'Alamat Utama',
  'profile.addressPlaceholder': 'Masukkan alamat',
  'profile.processing': 'Memproses...',
  'profile.save': 'Simpan Profil',

  // Commodities
  'commodities.title': 'Komoditas',
  'commodities.subtitle': 'Kelola komoditas pertanian Anda',
  'commodities.add': 'Tambah Komoditas',
  'commodities.name': 'Nama',
  'commodities.type': 'Jenis',
  'commodities.quantity': 'Jumlah',
  'commodities.location': 'Lokasi',
  'commodities.grade': 'Grade',
  'commodities.action': 'Aksi',
  'commodities.search': 'Cari komoditas...',
  'commodities.detail': 'Detail Komoditas',
  'commodities.qrcode': 'QR Code',
  'commodities.unit': 'Satuan',
  'commodities.created': 'Tanggal Dibuat',
  'commodities.harvestDate': 'Tanggal Panen',
  'commodities.upload.image': 'Unggah foto komoditas',
  'commodities.upload.grade': 'Unggah file grading',
  'commodities.list': 'Daftar Komoditas',
  'commodities.notfound': 'Tidak ada komoditas yang ditemukan',
  'commodities.history': 'Riwayat Transaksi',
  'commodities.export': 'Ekspor Data',
  'commodities.import': 'Impor Data',
  'commodities.filter': 'Filter Komoditas',
  'commodities.sort': 'Urutkan Berdasarkan',
  'commodities.harvest': 'Tanggal Panen',
  'commodities.origin': 'Asal',
  'commodities.category': 'Kategori',
  'commodities.imageUrl': 'Gambar Komoditas',
  'commodities.stock': 'Total Stok',
  'commodities.pricePerUnit': 'Harga per Unit',
  'commodities.price': 'Harga',
  'commodities.certifications': 'Sertifikasi',
  'commodities.description': 'Deskripsi',
  'commodities.qrcodeDesc': 'Gunakan QR Code ini untuk melacak komoditas Anda.',
  'commodities.addDesc':
    'Isi formulir di bawah ini untuk menambahkan komoditas baru ke daftar Anda.',
  'commodities.namePlaceholder': 'Masukkan nama komoditas',
  'commodities.unitPlaceholder': 'Pilih satuan',
  'commodities.categoryPlaceholder': 'Pilih kategori',
  'commodities.gradePlaceholder': 'Level Grade cth: A, B, C',
  'commodities.harvestDatePlaceholder': 'Pilih tanggal',
  'commodities.descriptionPlaceholder': 'Deskripsi komoditas',
  'commodities.basePrice': 'Harga Dasar',
  'commodities.stockPlaceholder': 'Masukkan stok',
  'commodities.setBulkPrice': 'Atur Harga Grosir',
  'commodities.bulkPrice': 'Harga Grosir',
  'commodities.addBulkPrice': 'Tambah Harga Grosir',
  'commodities.bulkPriceList': 'Daftar Harga Grosir',
  'commodities.noBulkPrice': 'Belum ada harga grosir',
  'commodities.addBulkPriceHint': 'Tambahkan harga grosir untuk menarik pembeli dalam jumlah besar',
  'commodities.basePriceInfo': 'Harga ini berlaku untuk pembelian standar.',
  'commodities.minQuantity': 'Jumlah Minimal',
  'commodities.minQuantityPlaceholder': '100',
  'commodities.bulkPricePerUnit': 'Harga per {{unit}}',
  'commodities.bulkPriceAuto': 'Harga akan otomatis diterapkan berdasarkan jumlah pembelian.',
  'commodities.saveBulkPrice': 'Simpan Harga Grosir',
  'commodities.error': 'Kesalahan',
  'commodities.nameRequired': 'Nama komoditas wajib diisi',
  'commodities.addSuccessTitle': 'Komoditas berhasil ditambahkan',
  'commodities.addSuccessDesc': '{{name}} telah ditambahkan ke daftar komoditas Anda',
  'commodities.addFailed': 'Gagal menambahkan komoditas',
  'commodities.attention': 'Perhatian',
  'commodities.fillBasePriceAndUnit': 'Harap isi harga dasar dan satuan terlebih dahulu',
  'commodities.uploadSuccessTitle': 'Unggah Berhasil',
  'commodities.uploadSuccessDesc': 'Gambar komoditas berhasil diunggah',
  'commodities.uploadFailed': 'Gagal mengunggah gambar',
  'commodities.uploadingImage': 'Mengunggah gambar...',
  'commodities.selectedFile': 'File terpilih',
  'commodities.dropHere': 'Jatuhkan file di sini...',
  'commodities.dragDropOrClick': 'Seret dan lepas file di sini, atau klik untuk memilih file',

  // Market
  'market.title': 'Pasar Komoditas',
  'market.subtitle': 'Jelajahi dan beli komoditas pertanian berkualitas langsung dari petani.',
  'market.seeCurrentPrices': 'Lihat Harga Terkini',
  'market.searchPlaceholder': 'Cari komoditas...',
  'market.filter': 'Filter',
  'market.noImage': 'Tidak ada gambar',
  'market.farmer': 'Petani:',
  'market.location': 'Lokasi:',
  'market.stock': 'Stok:',
  'market.details': 'Detail',
  'market.loadMore': 'Muat Lebih Banyak',
  'market.loading': 'Memuat komoditas...',
  'market.noCommodities': 'Tidak ada komoditas ditemukan',
  'market.search': 'Cari komoditas...',
  'market.sort': 'Urutkan',
  'market.currentPrices': 'Lihat Harga Terkini',
  'market.price': 'Harga',
  'market.buy': 'Beli',
  'market.noResults': 'Tidak ada komoditas yang ditemukan',
  'market.minOrder': 'Pembelian minimum',
  'market.certifications': 'Sertifikasi',
  'market.harvestDate': 'Tanggal Panen',
  'market.variety': 'Varietas',
  'market.grade': 'Grade',
  'market.description': 'Deskripsi',
  'market.nutrition': 'Nutrisi',
  'market.storage': 'Penyimpanan',
  'market.buyNow': 'Beli Sekarang',
  'market.contactFarmer': 'Hubungi Petani',
  'market.viewAllProducts': 'Lihat Semua Produk',
  'market.farmerInfo': 'Informasi Petani',
  'market.memberSince': 'Bergabung sejak',
  'market.transactions': 'transaksi',
  'market.reviews': 'Ulasan Pembeli',
  'market.noReviews': 'Belum ada ulasan',
  'market.backToMarket': 'Kembali ke Pasar',
  'market.notFound': 'Komoditas tidak ditemukan',
  'marketDetail.loading': 'Memuat detail komoditas...',
  'marketDetail.notFound': 'Komoditas tidak ditemukan',
  'marketDetail.backToMarket': 'Kembali ke Pasar',
  'marketDetail.noImage': 'Tidak ada gambar',
  'marketDetail.farmer': 'Petani',
  'marketDetail.location': 'Lokasi',
  'marketDetail.stock': 'Stok',
  'marketDetail.harvestDate': 'Tanggal Panen',
  'marketDetail.loadingPrice': 'Memuat harga...',
  'marketDetail.price': 'Harga',
  'marketDetail.totalPrice': 'Harga Total',
  'marketDetail.processing': 'Memproses...',
  'marketDetail.placeOrder': 'Pesan & Bayar',
  'marketDetail.description': 'Deskripsi',
  'marketDetail.noDescription': 'Tidak ada deskripsi.',
  'marketDetail.farmerInfo': 'Informasi Petani',
  'marketDetail.memberSince': 'Bergabung sejak',
  'marketDetail.transactions': 'transaksi',
  'marketDetail.contactFarmer': 'Hubungi Petani',
  'marketDetail.viewAllProducts': 'Lihat Semua Produk',
  'marketDetail.error': 'Kesalahan',
  'marketDetail.notLoggedIn': 'Pengguna belum login atau profil belum lengkap.',
  'marketDetail.noCommodityOrQuantity': 'Data komoditas belum dimuat atau jumlah belum dipilih.',
  'marketDetail.processingOrder': 'Memproses Pesanan...',
  'marketDetail.pleaseWait': 'Mohon tunggu.',
  'marketDetail.failedPrepareOrder': 'Gagal menyiapkan pesanan di server.',
  'marketDetail.awaitingPayment': 'Menunggu Pembayaran...',
  'marketDetail.confirmInWallet': 'Silakan konfirmasi transaksi di dompet Anda.',
  'marketDetail.paymentSecured': 'Pembayaran Berhasil Diamankan!',
  'marketDetail.escrowInitialized': 'Escrow diinisialisasi. Tx: {{tx}}...',
  'marketDetail.missingPda': 'Alamat PDA hilang setelah transaksi.',
  'marketDetail.orderUpdated': 'Pesanan Diperbarui',
  'marketDetail.convexUpdated': 'Catatan Convex diperbarui.',
  'marketDetail.failedUpdateConvex': 'Gagal memperbarui status pesanan di Convex.',
  'marketDetail.paymentFailed': 'Pembayaran Gagal',
  'marketDetail.couldNotInitEscrow': 'Tidak dapat menginisialisasi escrow.',
  'marketDetail.txSubmitted': 'Transaksi Dikirim',
  'marketDetail.txAwaiting': 'Tx: {{tx}}... Menunggu konfirmasi.',
  'marketDetail.orderFailed': 'Pesanan Gagal',
  'marketDetail.couldNotPlaceOrder': 'Tidak dapat memproses pesanan.',

  // Transactions
  'transactions.title': 'Transaksi',
  'transactions.subtitle': 'Kelola transaksi komoditas Anda',
  'transactions.id': 'ID Transaksi',
  'transactions.type': 'Tipe',
  'transactions.commodity': 'Komoditas',
  'transactions.quantity': 'Jumlah',
  'transactions.price': 'Harga',
  'transactions.status': 'Status',
  'transactions.buyer': 'Pembeli',
  'transactions.seller': 'Penjual',
  'transactions.date': 'Tanggal',
  'transactions.action': 'Aksi',
  'transactions.search': 'Cari transaksi...',
  'transactions.detail': 'Detail Transaksi',
  'transactions.all': 'Semua',
  'transactions.pending': 'Menunggu',
  'transactions.processed': 'Diproses',
  'transactions.completed': 'Selesai',
  'transactions.canceled': 'Dibatalkan',
  'transactions.total': 'Total Harga',
  'transactions.terms': 'Syarat & Ketentuan',
  'transactions.notfound': 'Tidak ada transaksi yang ditemukan',
  'transactions.filters': 'Filter Transaksi',
  'transactions.payment': 'Metode Pembayaran',
  'transactions.timeline': 'Timeline Transaksi',
  'transactions.documents': 'Dokumen',
  'transactions.notes': 'Catatan',
  'transactions.invoice': 'Faktur',
  'transactions.empty': 'Tidak ada transaksi yang ditemukan',
  'transactions.new': 'Transaksi Baru',
  'transactions.regular': 'Reguler',
  'transactions.list': 'Daftar Transaksi',
  'transactions.print': 'Cetak Transaksi',
  'transactions.updatedAt': 'Tanggal Diperbarui',
  'transactions.summary': 'Ringkasan Transaksi',

  // Order Book
  'orderbook.title': 'Order Book',
  'orderbook.subtitle': 'Lihat dan terima permintaan komoditas dari pembeli',
  'orderbook.id': 'ID Order',
  'orderbook.counterparty': 'Counterparty',
  'orderbook.seller': 'Penjual',
  'orderbook.amount': 'Harga Total',
  'orderbook.buyer': 'Pembeli',
  'orderbook.commodity': 'Komoditas',
  'orderbook.quantity': 'Jumlah',
  'orderbook.grade': 'Grade yang Diminta',
  'orderbook.delivery': 'Tanggal Pengiriman',
  'orderbook.expiry': 'Tanggal Kedaluwarsa',
  'orderbook.status': 'Status',
  'orderbook.action': 'Aksi',
  'orderbook.search': 'Cari order book...',
  'orderbook.detail': 'Detail Order Book',
  'orderbook.list': 'Daftar Order Book',
  'orderbook.all': 'Semua',
  'orderbook.open': 'Terbuka',
  'orderbook.accepted': 'Diterima',
  'orderbook.completed': 'Selesai',
  'orderbook.expired': 'Kedaluwarsa',
  'orderbook.terms': 'Syarat & Ketentuan',
  'orderbook.notfound': 'Tidak ada order book yang ditemukan',
  'orderbook.filter': 'Filter Order',
  'orderbook.sort': 'Urutkan Berdasarkan',
  'orderbook.create': 'Buat Order',
  'orderbook.price': 'Harga Permintaan',
  'orderbook.total': 'Total Nilai',
  'orderbook.offers': 'Penawaran',
  'orderbook.respond': 'Tanggapi Order',

  // Shipping
  'shipping.title': 'Pengiriman',
  'shipping.subtitle': 'Lacak dan kelola pengiriman Anda',
  'shipping.id': 'ID Pengiriman',
  'shipping.origin': 'Asal',
  'shipping.destination': 'Tujuan',
  'shipping.status': 'Status',
  'shipping.carrier': 'Kurir',
  'shipping.tracking': 'Nomor Pelacakan',
  'shipping.departureDate': 'Tanggal Keberangkatan',
  'shipping.arrivalDate': 'Perkiraan Kedatangan',
  'shipping.commodity': 'Komoditas',
  'shipping.weight': 'Berat',
  'shipping.cost': 'Biaya Pengiriman',
  'shipping.documents': 'Dokumen',
  'shipping.notfound': 'Tidak ada pengiriman yang ditemukan',
  'shipping.create': 'Buat Pengiriman',
  'shipping.detail': 'Detail Pengiriman',
  'shipping.updateStatus': 'Perbarui Status',
  'shipping.trackShipment': 'Lacak Pengiriman',
  'shipping.vehicle': 'Jenis Kendaraan',
  'shipping.driverInfo': 'Informasi Pengemudi',
  'shipping.contact': 'Kontak',
  'shipping.instructions': 'Instruksi Khusus',
  'shipping.route': 'Informasi Rute',
  'shipping.stops': 'Tempat Pemberhentian',
  'shipping.history': 'Riwayat Status',

  // Prices
  'prices.title': 'Harga Pasar',
  'prices.name': 'Nama Komoditas',
  'prices.price': 'Harga',
  'prices.unit': 'Satuan',
  'prices.subtitle': 'Lihat harga komoditas saat ini',
  'prices.commodity': 'Komoditas',
  'prices.category': 'Kategori',
  'prices.currentPrice': 'Harga Saat Ini',
  'prices.change': 'Perubahan 24 Jam',
  'prices.volume': 'Volume 24 Jam',
  'prices.high': 'Tertinggi 24 Jam',
  'prices.action': 'Aksi',
  'prices.low': 'Terendah 24 Jam',
  'prices.region': 'Wilayah',
  'prices.grade': 'Grading',
  'prices.chart': 'Grafik Harga',
  'prices.history': 'Riwayat Harga',
  'prices.forecast': 'Perkiraan Harga',
  'prices.market': 'Pasar',
  'prices.date': 'Terakhir Diperbarui',
  'prices.notfound': 'Tidak ada harga komoditas yang ditemukan',
  'prices.source': 'Sumber Data',
  'prices.filter': 'Filter Harga',
  'prices.compare': 'Bandingkan',
  'prices.watchlist': 'Tambah ke Watchlist',
  'prices.trends': 'Tren Pasar',
  'prices.notifications': 'Notifikasi Harga',
  'prices.searchPlaceholder': 'Cari komoditas atau wilayah...',
  'prices.viewDetail': 'Lihat detail harga',

  // Status labels
  'status.open': 'Terbuka',
  'status.accepted': 'Diterima',
  'status.completed': 'Selesai',
  'status.expired': 'Kedaluwarsa',
  'status.canceled': 'Dibatalkan',
  'status.pending': 'Menunggu',
  'status.confirmed': 'Dikonfirmasi',
  'status.paid': 'Dibayar',
  'status.shipped': 'Dikirim',
  'status.received': 'Diterima',
  'status.processing': 'Diproses',
  'status.notshipped': 'Belum Dikirim',
  'status.shipping': 'Sedang Dikirim',
  'status.delivered': 'Terkirim',
  'status.inTransit': 'Dalam Perjalanan',
  'status.outForDelivery': 'Siap Antar',
  'status.failed': 'Gagal',
  'status.delayed': 'Tertunda',
  'status.returned': 'Dikembalikan',
  'status.approved': 'Disetujui',
  'status.rejected': 'Ditolak',
  'status.draft': 'Draf',
  'status.onHold': 'Ditahan',
  'status.negotiating': 'Negosiasi',

  // Dashboard
  'dashboard.title': 'Dasbor',
  'dashboard.welcome': 'Selamat datang kembali,',
  'dashboard.summary': 'Ringkasan Pemasukkan',
  'dashboard.recentTransactions': 'Transaksi Terbaru',
  'dashboard.pendingOrders': 'Pesanan Tertunda',
  'dashboard.upcomingShipments': 'Pengiriman Mendatang',
  'dashboard.marketInsights': 'Wawasan Pasar',
  'dashboard.commodityStatus': 'Status Komoditas',
  'dashboard.analytics': 'Analitik',
  'dashboard.quickActions': 'Aksi Cepat',
  'dashboard.alerts': 'Peringatan',
  'dashboard.recommendations': 'Rekomendasi',
  'dashboard.expenseSummary': 'Ringkasan Pengeluaran',
  'transactions.inDelivery': 'Sedang dikirim',
  'transactions.status.selesai': 'Selesai',
  'transactions.status.dibatalkan': 'Dibatalkan',
  'transactions.status.negosiasi': 'Negosiasi',
  'transactions.status.menunggu_konfirmasi': 'Menunggu Konfirmasi',
  'transactions.status.dikonfirmasi': 'Dikonfirmasi',
  'transactions.status.dibayar': 'Dibayar',
  'transactions.status.persiapan_pengiriman': 'Persiapan Pengiriman',
  'transactions.status.sedang_dikirim': 'Sedang Dikirim',
  'transactions.status.sudah_dikirim': 'Sudah Dikirim',
  'transactions.status.diterima': 'Diterima',

  // Profile/Account
  'profile.title': 'Profil',
  'profile.personalInfo': 'Informasi Pribadi',
  'profile.company': 'Informasi Perusahaan',
  'profile.security': 'Keamanan',
  'profile.preferences': 'Preferensi',
  'profile.notifications': 'Notifikasi',
  'profile.paymentMethods': 'Metode Pembayaran',
  'profile.accountHistory': 'Riwayat Akun',
  'profile.documents': 'Dokumen',
  'profile.settings': 'Pengaturan Akun',
  'profile.help': 'Bantuan & Dukungan',
  'profile.logout': 'Keluar',
  'profile.editProfile': 'Edit Profil',
  'profile.changePassword': 'Ubah Kata Sandi',
  'profile.language': 'Bahasa',
  'profile.theme': 'Tema',
  'profile.verifications': 'Verifikasi',

  // Balance/Finance
  'balance.title': 'Saldo',
  'balance.available': 'Saldo Tersedia',
  'balance.pending': 'Tertunda',
  'balance.totalValue': 'Total Nilai',
  'balance.transactions': 'Riwayat Transaksi',
  'balance.withdraw': 'Tarik',
  'balance.deposit': 'Setor',
  'balance.transfer': 'Transfer',
  'balance.statement': 'Laporan',
  'balance.paymentMethods': 'Metode Pembayaran',
  'balance.settings': 'Pengaturan Pembayaran',
  'balance.currency': 'Mata Uang',
  'balance.exchange': 'Nilai Tukar',

  // Time and dates
  'time.today': 'Hari Ini',
  'time.yesterday': 'Kemarin',
  'time.tomorrow': 'Besok',
  'time.thisWeek': 'Minggu Ini',
  'time.lastWeek': 'Minggu Lalu',
  'time.thisMonth': 'Bulan Ini',
  'time.lastMonth': 'Bulan Lalu',
  'time.thisYear': 'Tahun Ini',
  'time.lastYear': 'Tahun Lalu',
  'time.custom': 'Rentang Kustom',

  // Charts and Analytics
  'charts.dailyPrices': 'Harga Harian',
  'charts.monthlyVolume': 'Volume Bulanan',
  'charts.commodityDistribution': 'Distribusi Komoditas',
  'charts.transactionTrends': 'Tren Transaksi',
  'charts.marketComparison': 'Perbandingan Pasar',
  'charts.supplyDemand': 'Penawaran & Permintaan',
  'charts.seasonalTrends': 'Tren Musiman',
  'charts.priceForecasts': 'Perkiraan Harga',
  'charts.exportImport': 'Rasio Ekspor/Impor',
  'charts.incomeExpenses': 'Pendapatan & Pengeluaran',

  // Errors and notifications
  'error.generic': 'Terjadi kesalahan',
  'error.notFound': 'Tidak ditemukan',
  'error.unauthorized': 'Akses tidak sah',
  'error.forbidden': 'Akses dilarang',
  'error.validation': 'Kesalahan validasi',
  'error.network': 'Kesalahan jaringan',
  'error.serverError': 'Kesalahan server',
  'error.timeout': 'Waktu permintaan habis',
  'error.unavailable': 'Layanan tidak tersedia',
  'success.saved': 'Berhasil disimpan',
  'success.created': 'Berhasil dibuat',
  'success.updated': 'Berhasil diperbarui',
  'success.deleted': 'Berhasil dihapus',
  'info.processing': 'Memproses permintaan Anda',
  'info.noData': 'Tidak ada data tersedia',
  'warning.unsaved': 'Anda memiliki perubahan yang belum disimpan',

  // Transaction Flow Explainer
  'flow.title': 'Proses Transaksi',
  'flow.subtitle': 'Berikut adalah cara kerja proses transaksi dari awal hingga akhir:',
  'flow.current': 'Langkah Saat Ini',
  'flow.helpTitle': 'Butuh bantuan?',
  'flow.helpText':
    'Jika Anda membutuhkan bantuan pada langkah mana pun dalam proses ini, silakan hubungi tim dukungan kami melalui pusat bantuan atau WhatsApp.',

  'flow.pending.title': '1. Pesanan Diterima',
  'flow.pending.description':
    'Pembeli telah melakukan pemesanan untuk komoditas Anda. Tinjau detail pesanan dan putuskan untuk menerima atau menolak.',

  'flow.confirmed.title': '2. Pesanan Dikonfirmasi',
  'flow.confirmed.description':
    'Anda telah mengkonfirmasi pesanan. Pembeli telah diberi tahu dan menunggu informasi lebih lanjut.',

  'flow.negotiating.title': '3. Negosiasi Harga',
  'flow.negotiating.description':
    'Diskusikan dan negosiasikan syarat harga dengan pembeli hingga kedua belah pihak puas.',

  'flow.paid.title': '4. Pembayaran Diterima',
  'flow.paid.description':
    'Pembeli telah melakukan pembayaran untuk pesanan. Anda sekarang dapat melanjutkan dengan persiapan pengiriman.',

  'flow.processing.title': '5. Persiapan Pengiriman',
  'flow.processing.description':
    'Siapkan komoditas yang dipesan untuk pengiriman. Pastikan pengemasan dan dokumentasi yang tepat.',

  'flow.shipping.title': '6. Pengiriman dalam Perjalanan',
  'flow.shipping.description':
    'Komoditas sedang dalam perjalanan ke pembeli. Informasi pelacakan telah diberikan kepada pembeli.',

  'flow.shipped.title': '7. Pengiriman Terkirim',
  'flow.shipped.description': 'Pengiriman telah sampai di alamat yang ditentukan pembeli.',

  'flow.received.title': '8. Pesanan Diterima',
  'flow.received.description':
    'Pembeli telah mengkonfirmasi penerimaan komoditas dan sedang memeriksa barang.',

  'flow.completed.title': '9. Transaksi Selesai',
  'flow.completed.description':
    'Transaksi telah berhasil diselesaikan. Dana telah dilepaskan ke akun Anda.',
};
