import './globals.css';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { UiLayout } from '@/components/ui/ui-layout';
import { ReactQueryProvider } from './react-query-provider';
import { LanguageProvider } from '@/contexts/LanguageContext';

export const metadata = {
	title: 'Votedapp',
	description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
	{ label: 'Account', path: '/account' },
	{ label: 'Clusters', path: '/clusters' },
	{ label: 'Votedapp Program', path: '/votedapp' },
];

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
		>
			<body>
				<ReactQueryProvider>
					<ClusterProvider>
						<SolanaProvider>
							<LanguageProvider>{children}</LanguageProvider>
						</SolanaProvider>
					</ClusterProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
